apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: registry.ird.mu-sigma.com/mutalent/frontend
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
          command: ["nginx", "-g", "daemon off;"]
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
