export const leaveModalStyles = {
    dialogPaper: {
        borderRadius: "2vh",
        //width: "45vw",
        maxWidth: "45vh",
        padding: "3vh",
        position: "relative" as "relative",
        height:"47vh",
    },
    header: {
        display: "flex",
        gap: "2vh",
        alignItems: "flex-start",
        marginBottom: "1vh",
    },
    warningIconBox: {
        width: "5vh",
        height: "5vh",
        backgroundColor: "#fff9e6",
        borderRadius: "1.5vh",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        color: "#ffa000",
        border: "0.1vh solid #ffe0b2",
        flexShrink: 0,
    },
    title: {
        fontSize: "2vh",
        fontWeight: 700,
        color: "#111",
        lineHeight: 1.2,
    },
    subtitle: {
        fontSize: "1.6vh",
        color: "#888",
        marginTop: "0.5vh",
    },
    description: {
        fontSize: "1.5vh",
        color: "#555",
        marginBottom: "3.5vh",
        lineHeight: 1.5,
    },
    optionCard: (selected: boolean, type: "save" | "delete") => ({
        display: "flex",
        alignItems: "center",
        gap: "2vh",
        padding: "1vh",
        borderRadius: "2vh",
       // borderColor:"#e6f2f1"
        border: `0.2vh solid ${selected ? (type === "save" ? "#006b66" : "#800000BF") : "#00766433"}`,
        backgroundColor: selected ? (type === "save" ? "#00766408" : "#fff5f5") : "#00766408",
        cursor: "pointer",
        marginBottom: "1vh",
        transition: "all 0.2s ease-in-out",
        "&:hover": {
           // borderColor: type === "save" ? "#006b66" : "#f44336",
        },
    }),

    optionCarddelete: (selected: boolean, type: "save" | "delete") => ({
        display: "flex",
        alignItems: "center",
        gap: "2vh",
        padding: "1vh",
        borderRadius: "2vh",
        
       // borderColor:"#e6f2f1"
        border: `0.2vh solid ${selected ? (type === "save" ? "#006b66" : "#800000BF") : "#800000BF"}`,
        backgroundColor: selected ? (type === "save" ? "#f0f9f8" : "#fff5f5") : "#FEF2F24D",
        cursor: "pointer",
        marginBottom: "1vh",
        transition: "all 0.2s ease-in-out",
        "&:hover": {
           // borderColor: type === "save" ? "#006b66" : "#f44336",
        },
    }),
    optionIconBox: (type: "save" | "delete") => ({
        width: "5vh",
        height: "5vh",
        backgroundColor: type === "save" ? "#e6f2f1" : "#fff1f1",
        borderRadius: "1.2vh",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        color: type === "save" ? "#006b66" : "#d32f2f",
        flexShrink: 0,
    }),
    optionContent: {
        flex: 1,
    },
    optionTitle: {
        fontSize: "1.7vh",
        fontWeight: 900,
        color:"#1E2939",
    },
    optionTitledelete: {
        fontSize: "1.7vh",
        fontWeight: 900,
        color:"#A62021",
    },
    optionSubtitle: {
        fontSize: "1.4vh",
        color: "#888",
        marginTop: "0.4vh",
    },
    radioCircle: (selected: boolean, type: "save" | "delete") => ({
        width: "2.4vh",
        height: "2.4vh",
        borderRadius: "50%",
        border: `0.2vh solid ${selected ? (type === "save" ? "#006b66" : "#f44336") : "#0076644D"}`,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        "&::after": {
            content: '""',
            width: "1.2vh",
            height: "1.2vh",
            borderRadius: "50%",
            backgroundColor: selected ? (type === "save" ? "#006b66" : "#f44336") : "transparent",
        },
    }),

    radioCircledelete: (selected: boolean, type: "save" | "delete") => ({
        width: "2.4vh",
        height: "2.4vh",
        borderRadius: "50%",
        border: `0.2vh solid ${selected ? (type === "save" ? "#006b66" : "#800000") : "#FFC9C9"}`,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        "&::after": {
            content: '""',
            width: "1.2vh",
            height: "1.2vh",
            borderRadius: "50%",
            backgroundColor: selected ? (type === "save" ? "#800000" : "#800000BF") : "transparent",
        },
    }),
    keepEditingBtn: {
        display: "block",
        margin: "0vh auto 0",
        textTransform: "none",
        fontSize: "1.7vh",
        fontWeight: 600,
        color: "#99A1AF",
        "&:hover": {
            backgroundColor: "transparent",
            textDecoration: "underline",
        },
    },
    closeIcon: {
        position: "absolute" as "absolute",
        right: "2vh",
        top: "2vh",
        color: "#ccc",
    },
};
