import { globalStyles } from "../config";

export const savedDraftsStyles = {
    root: {
        width: "100%",
        height: "100%",
        backgroundColor: "#fcfcfc",
        display: "flex",
        flexDirection: "column",
        // Padding removed from root to make container flush with sidebar
    },
    header: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        padding: "2.5vh 3vh",
        backgroundColor: "#fff",
        borderBottom: "0.1vh solid #f0f0f0",
    },
    headerLeft: {
        display: "flex",
        alignItems: "center",
        gap: "1.5vh",
    },
    iconBox: {
        width: "4vh",
        height: "4vh",
        backgroundColor: "#006b66",
        borderRadius: "1vh",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        color: "#fff",
        boxShadow: "0 0.4vh 1.2vh rgba(0, 107, 102, 0.2)",
    },
    title: {
        fontFamily: "Poppins, sans-serif",
        fontSize: "2vh",
        fontWeight: 600,
        color: "#111111",
        lineHeight: 1.2,
    },
    subtitle: {
        fontSize: "1.3vh",
        color: "#888",
    },
    searchContainer: {
        width: "100%",
        padding: "3vh 3vh 0",
        marginBottom: "1vh",
    },
    searchInput: {
        width: "100%",
        backgroundColor: "#fff",
        borderRadius: "1.2vh",
        border: "0.15vh solid #eee",
        padding: "0.2vh 2vh",
        fontSize: "1.6vh",
        color: "#444",
        display: "flex",
        alignItems: "center",
        gap: "1.5vh",
        boxShadow: "0 0.2vh 0.6vh rgba(0,0,0,0.02)",
        "&:focus-within": {
            borderColor: "#006b66",
            boxShadow: "0 0.4vh 1vh rgba(0, 107, 102, 0.05)",
        }
    },
    createButton: {
        backgroundColor: "#006b66",
        color: "#ffffff",
        borderRadius: "1vh",
        textTransform: "none",
        padding: "0.5vh 1.5vh",
        fontSize: "1.7vh",
        fontWeight: 500,
        display: "flex",
        alignItems: "center",
        // gap: "0.8vh",
        boxShadow: "0 0.4vh 1.2vh rgba(0, 107, 102, 0.15)",
        "&:hover": {
            backgroundColor: "#005752",
        },
    },
    content: {
        flex: 1,
        width: "100%",
        overflowY: "auto",
        padding: "2vh 3vh 4vh",
    },
    gridContainer: {
        width: "100%",
        display: "grid",
        gridTemplateColumns: "repeat(3, 1fr)",
        gap: "2.5vh",
    },
    draftCard: {
        backgroundColor: "#fff",
        borderRadius: "1.2vh",
        border: "0.15vh solid #f0f0f0",
        padding: "2.5vh 3vh 0.5vh",
        position: "relative",
        //transition: "all 0.3s ease",
        display: "flex",
        flexDirection: "column",
        gap: "1.5vh",
       // height: "auto",
       // minHeight: "22vh",
        boxShadow: "0 0.8vh 2.4vh rgba(0, 0, 0, 0.04)",
        "&:hover": {
            borderColor: "#006b66",
            boxShadow: "0 1.2vh 3vh rgba(0, 107, 102, 0.08)",
        },
        "&::before": {
            content: '""',
            position: "absolute",
            top: 0,
            left: 0,
            right: 0,
            height: "0.5vh",
            backgroundColor: "#006b66",
            borderRadius: "1.2vh 1.2vh 0 0",
        }
    },
    cardHeader: {
        display: "flex",
        alignItems: "center",
        gap: "1.5vh",
    },
    cardIconBox: {
        width: "4vh",
        height: "4vh",
        backgroundColor: "#E6F4F3",
        borderRadius: "1vh",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        color: "#006b66",
        flexShrink: 0,
        border: "1px solid #cceae7",
    },
    cardTitle: {
        fontFamily: "Poppins, sans-serif",
        fontSize: "1.5vh",
        fontWeight: 600,
        color: "#374151",
        flex: 1,
        lineHeight: 1.4,
    },
    deleteBtn: {
        color: "#006b66",
        backgroundColor: "#fff",
        border: "1px solid #E5E7EB",
        borderRadius: "1.2vh",
        padding: "0.8vh",
        width: "4.5vh",
        height: "4.5vh",
        "&:hover": {
            backgroundColor: "#f9fafb",
            borderColor: "#d1d5db",
        }
    },
    tagContainer: {
        display: "flex",
        flexWrap: "wrap",
        gap: "1vh",
    },
    tag: {
        padding: "0.4vh 1.2vh",
        borderRadius: "0.8vh",
        fontSize: "1.1vh",
        fontWeight: 600,
        backgroundColor: "#F3F4F6",
        color: "#6B7280",
        display: "flex",
        alignItems: "center",
        height: "2.5vh",
    },
    premiumTag: {
        backgroundColor: "#E6F4F3",
        color: "#006b66",
    },
    progressSection: {
        width: "100%",
        display: "flex",
        flexDirection: "column",
        gap: "0.5vh",
    },
    progressBarContainer: {
        width: "100%",
        height: "0.6vh",
        backgroundColor: "#F3F4F6",
        borderRadius: "1vh",
        overflow: "hidden",
        position: "relative",
    },
    progressBar: (value: number) => ({
        width: `${value}%`,
        height: "100%",
        backgroundColor: "#006b66",
        borderRadius: "1vh",
        transition: "width 0.8s cubic-bezier(0.4, 0, 0.2, 1)",
    }),
    progressMetadata: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
    },
    progressPercent: {
        fontSize: "1.6vh",
        fontWeight: 700,
        color: "#006b66",
        order: 2,
    },
    stoppedAt: {
        fontSize: "1.2vh",
        color: "#6B7280",
        order: 1,
    },
    stoppedAtHighlight: {
        fontWeight: 700,
        color: "#374151",
    },
    savedAtContainer: {
        display: "flex",
        alignItems: "center",
        gap: "0.8vh",
        color: "#9CA3AF",
    },
    savedAt: {
        fontSize: "1.2vh",
        color: "#9CA3AF",
    },
    continueBtn: {
        backgroundColor: "#006b66",
        color: "#fff",
        borderRadius: "1vh",
        textTransform: "none",
        flex: 1,
        height: "3vh",
        fontSize: "1.5vh",
        fontWeight: 700,
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        boxShadow: "none",
        maxWidth:"35vh",
        "&:hover": {
            backgroundColor: "#005752",
            boxShadow: "0 0.4vh 1.2vh rgba(0, 107, 102, 0.2)",
        }
    },
    emptyState: {
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        padding: "10vh 0",
    },
    emptyIconBox: {
        width: "12vh",
        height: "12vh",
        backgroundColor: "#f9f9f9",
        borderRadius: "2vh",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        marginBottom: "3vh",
    },
    emptyTitle: {
        fontSize: "2.2vh",
        fontWeight: 600,
        color: "#333",
        marginBottom: "1vh",
    },
    emptySubtitle: {
        fontSize: "1.6vh",
        color: "#888",
        textAlign: "center",
        maxWidth: "40vh",
        marginBottom: "4vh",
        lineHeight: 1.5,
    },
    centerCreateButton: {
        backgroundColor: "#006b66",
        color: "#ffffff",
        borderRadius: "0.8vh",
        textTransform: "none",
        padding: "1vh 3.5vh",
        fontSize: "1.8vh",
        fontWeight: 500,
        display: "flex",
        alignItems: "center",
        gap: "1vh",
        "&:hover": {
            backgroundColor: "#005752",
        },
    },

    backButton: {
        width: "4.2vh",
        height: "4.2vh",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        borderRadius: "1.2vh",
        border: "0.15vh solid #E5E7EB",
        backgroundColor: "#fff",
        color: "#374151",
        padding: "0.6vh",
        marginRight: "1.5vh",
        "&:hover": {
            backgroundColor: "#f9fafb",
            borderColor: "#d1d5db",
        },
    },
    backIcon: {
        fontSize: "1.8vh",
        marginLeft: "0.4vh",
    },
};
