export const sidebarstyles = {
  box: {
    width: "5vw",
    height: "92vh",
    color: "white",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    alignItems: "center",
    py: '2vh',
    position: "sticky",
    top:"7vh",
    borderRight: "0.1vh solid #7d91aa",
  },
  logo: {
    width: "5.5vw",
    // height: "10vh",
  },
  box1: {
    flexGrow: 1,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    //gap: "2vh",
    width: "4.9vw",
  },
  box2: {
    // cursor: "pointer",
    position: "relative",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    height: "10vh",
    "&:hover": { bgcolor: "#e7e9ec" },
  },
  box3: {
    position: "absolute",
    right: 0,
    top: "25%",
    bottom: "25%",
    width: "0.5vh",
   // bgcolor: "#75818F",
    bgcolor: "#006B66",
    borderRadius: "0 0.5vh 0.5vh 0",
  },
};
